from typing import Any, Callable, Tuple, List

VERTEX_BUFFER_POS_OFFSET: int
VERTEX_BUFFER_UV_OFFSET: int
VERTEX_BUFFER_COL_OFFSET: int
VERTEX_SIZE: int
INDEX_SIZE: int

def accept_drag_drop_payload(type_: str, flags: int=0) -> _ImGuiPayload: ...
def align_text_to_frame_padding() -> None: ...
def arrow_button(str_id: str, dir_: int) -> Any: ...
def begin(name: str, p_open: Any=None, flags: int=0) -> Any: ...
def begin_child_frame(id_: int, size: tuple, flags: int=0) -> Any: ...
def begin_child_id(id_: int, size: tuple=(0, 0), border: Any=False, flags: int=0) -> Any: ...
def begin_child_str(str_id: str, size: tuple=(0, 0), border: Any=False, flags: int=0) -> Any: ...
def begin_combo(label: str, preview_value: str, flags: int=0) -> Any: ...
def begin_disabled(disabled: Any=True) -> None: ...
def begin_drag_drop_source(flags: int=0) -> Any: ...
def begin_drag_drop_target() -> Any: ...
def begin_group() -> None: ...
def begin_list_box(label: str, size: tuple=(0, 0)) -> Any: ...
def begin_main_menu_bar() -> Any: ...
def begin_menu(label: str, enabled: Any=True) -> Any: ...
def begin_menu_bar() -> Any: ...
def begin_popup(str_id: str, flags: int=0) -> Any: ...
def begin_popup_context_item(str_id: str=None, popup_flags: int=1) -> Any: ...
def begin_popup_context_void(str_id: str=None, popup_flags: int=1) -> Any: ...
def begin_popup_context_window(str_id: str=None, popup_flags: int=1) -> Any: ...
def begin_popup_modal(name: str, p_open: Any=None, flags: int=0) -> Any: ...
def begin_tab_bar(str_id: str, flags: int=0) -> Any: ...
def begin_tab_item(label: str, p_open: Any=None, flags: int=0) -> Any: ...
def begin_table(str_id: str, column: int, flags: int=0, outer_size: tuple=(0.0, 0.0), inner_width: float=0.0) -> Any: ...
def begin_tooltip() -> None: ...
def bullet() -> None: ...
def bullet_text(fmt: str) -> None: ...
def bullet_textv(fmt: str, args: str) -> None: ...
def button(label: str, size: tuple=(0, 0)) -> Any: ...
def calc_item_width() -> float: ...
def calc_text_size(pOut: _ImVec2, text: str, text_end: str=None, hide_text_after_double_hash: Any=False, wrap_width: float=-1.0) -> None: ...
def checkbox(label: str, value: Any) -> Any: ...
def checkbox_flags_int_ptr(label: str, flags: int, flags_value: int) -> Any: ...
def checkbox_flags_uint_ptr(label: str, flags: int, flags_value: int) -> Any: ...
def close_current_popup() -> None: ...
def collapsing_header_bool_ptr(label: str, p_visible: Any, flags: int=0) -> Any: ...
def collapsing_header_tree_node_flags(label: str, flags: int=0) -> Any: ...
def color_button(desc_id: str, col: tuple, flags: int=0, size: tuple=(0, 0)) -> Any: ...
def color_convert_float_4_to_u32(in_: tuple) -> int: ...
def color_convert_hs_vto_rgb(h: float, s: float, value: float, out_r: float, out_g: float, out_b: float) -> None: ...
def color_convert_rg_bto_hsv(r: float, g: float, b: float, out_h: float, out_s: float, out_v: float) -> None: ...
def color_convert_u32_to_float4(pOut: _ImVec4, in_: int) -> None: ...
def color_edit3(label: str, col0: float, col1: float, col2: float, flags: int=0) -> Any: ...
def color_edit4(label: str, col0: float, col1: float, col2: float, col3: float, flags: int=0) -> Any: ...
def color_picker3(label: str, col0: float, col1: float, col2: float, flags: int=0) -> Any: ...
def color_picker4(label: str, col0: float, col1: float, col2: float, col3: float, flags: int=0, ref_col: float=None) -> Any: ...
def columns(count: int=1, id_: str=None, border: Any=True) -> None: ...
def combo_fn_bool_ptr(label: str, current_item: int, items_getter: Callable, data: Any, items_count: int, popup_max_height_in_items: int=-1) -> Any: ...
def combo_str(label: str, current_item: int, items_separated_by_zeros: str, popup_max_height_in_items: int=-1) -> Any: ...
def combo_str_arr(label: str, current_item: int, items: Any, items_count: int, popup_max_height_in_items: int=-1) -> Any: ...
def create_context(shared_font_atlas: _ImFontAtlas=None) -> _ImGuiContext: ...
def debug_check_version_and_data_layout(version_str: str, sz_io: Any, sz_style: Any, sz_vec2: Any, sz_vec4: Any, sz_drawvert: Any, sz_drawidx: Any) -> Any: ...
def debug_text_encoding(text: str) -> None: ...
def destroy_context(ctx: _ImGuiContext=None) -> None: ...
def destroy_platform_windows() -> None: ...
def dock_space(id_: int, size: tuple=(0, 0), flags: int=0, window_class: _ImGuiWindowClass=None) -> int: ...
def dock_space_over_viewport(viewport: _ImGuiViewport=None, flags: int=0, window_class: _ImGuiWindowClass=None) -> int: ...
def drag_float(label: str, value: float, v_speed: float=1.0, v_min: float=0.0, v_max: float=0.0, format_: str="%.3", flags: int=0) -> Any: ...
def drag_float2(label: str, value0: float, value1: float, v_speed: float=1.0, v_min: float=0.0, v_max: float=0.0, format_: str="%.3", flags: int=0) -> Any: ...
def drag_float3(label: str, value0: float, value1: float, value2: float, v_speed: float=1.0, v_min: float=0.0, v_max: float=0.0, format_: str="%.3", flags: int=0) -> Any: ...
def drag_float4(label: str, value0: float, value1: float, value2: float, value3: float, v_speed: float=1.0, v_min: float=0.0, v_max: float=0.0, format_: str="%.3", flags: int=0) -> Any: ...
def drag_float_range2(label: str, v_current_min: float, v_current_max: float, v_speed: float=1.0, v_min: float=0.0, v_max: float=0.0, format_: str="%.3", format_max: str=None, flags: int=0) -> Any: ...
def drag_int(label: str, value: int, v_speed: float=1.0, v_min: int=0, v_max: int=0, format_: str="%d", flags: int=0) -> Any: ...
def drag_int2(label: str, value0: int, value1: int, v_speed: float=1.0, v_min: int=0, v_max: int=0, format_: str="%d", flags: int=0) -> Any: ...
def drag_int3(label: str, value0: int, value1: int, value2: int, v_speed: float=1.0, v_min: int=0, v_max: int=0, format_: str="%d", flags: int=0) -> Any: ...
def drag_int4(label: str, value0: int, value1: int, value2: int, value3: int, v_speed: float=1.0, v_min: int=0, v_max: int=0, format_: str="%d", flags: int=0) -> Any: ...
def drag_int_range2(label: str, v_current_min: int, v_current_max: int, v_speed: float=1.0, v_min: int=0, v_max: int=0, format_: str="%d", format_max: str=None, flags: int=0) -> Any: ...
def drag_scalar(label: str, data_type: int, p_data: Any, v_speed: float=1.0, p_min: Any=None, p_max: Any=None, format_: str=None, flags: int=0) -> Any: ...
def drag_scalarn(label: str, data_type: int, p_data: Any, components: int, v_speed: float=1.0, p_min: Any=None, p_max: Any=None, format_: str=None, flags: int=0) -> Any: ...
def dummy(size: tuple) -> None: ...
def end() -> None: ...
def end_child() -> None: ...
def end_child_frame() -> None: ...
def end_combo() -> None: ...
def end_disabled() -> None: ...
def end_drag_drop_source() -> None: ...
def end_drag_drop_target() -> None: ...
def end_frame() -> None: ...
def end_group() -> None: ...
def end_list_box() -> None: ...
def end_main_menu_bar() -> None: ...
def end_menu() -> None: ...
def end_menu_bar() -> None: ...
def end_popup() -> None: ...
def end_tab_bar() -> None: ...
def end_tab_item() -> None: ...
def end_table() -> None: ...
def end_tooltip() -> None: ...
def find_viewport_by_id(id_: int) -> _ImGuiViewport: ...
def find_viewport_by_platform_handle(platform_handle: Any) -> _ImGuiViewport: ...
def get_background_draw_list_nil() -> _ImDrawList: ...
def get_background_draw_list_viewport_ptr(viewport: _ImGuiViewport) -> _ImDrawList: ...
def get_clipboard_text() -> str: ...
def get_color_u32_col(idx: int, alpha_mul: float=1.0) -> int: ...
def get_color_u32_u32(col: int) -> int: ...
def get_color_u32_vec4(col: tuple) -> int: ...
def get_column_index() -> int: ...
def get_column_offset(column_index: int=-1) -> float: ...
def get_column_width(column_index: int=-1) -> float: ...
def get_columns_count() -> int: ...
def get_content_region_avail(pOut: _ImVec2) -> None: ...
def get_content_region_max(pOut: _ImVec2) -> None: ...
def get_current_context() -> _ImGuiContext: ...
def get_cursor_pos(pOut: _ImVec2) -> None: ...
def get_cursor_posx() -> float: ...
def get_cursor_posy() -> float: ...
def get_cursor_screen_pos(pOut: _ImVec2) -> None: ...
def get_cursor_start_pos(pOut: _ImVec2) -> None: ...
def get_drag_drop_payload() -> _ImGuiPayload: ...
def get_draw_data() -> _ImDrawData: ...
def get_draw_list_shared_data() -> _ImDrawListSharedData: ...
def get_font() -> _ImFont: ...
def get_font_size() -> float: ...
def get_font_tex_uv_white_pixel(pOut: _ImVec2) -> None: ...
def get_foreground_draw_list_nil() -> _ImDrawList: ...
def get_foreground_draw_list_viewport_ptr(viewport: _ImGuiViewport) -> _ImDrawList: ...
def get_frame_count() -> int: ...
def get_frame_height() -> float: ...
def get_frame_height_with_spacing() -> float: ...
def get_id_ptr(ptr_id: Any) -> int: ...
def get_id_str(str_id: str) -> int: ...
def get_id_str_str(str_id_begin: str, str_id_end: str) -> int: ...
def get_io() -> _ImGuiIO: ...
def get_item_id() -> int: ...
def get_item_rect_max(pOut: _ImVec2) -> None: ...
def get_item_rect_min(pOut: _ImVec2) -> None: ...
def get_item_rect_size(pOut: _ImVec2) -> None: ...
def get_key_index(key: Any) -> Any: ...
def get_key_name(key: Any) -> str: ...
def get_key_pressed_amount(key: Any, repeat_delay: float, rate: float) -> int: ...
def get_main_viewport() -> _ImGuiViewport: ...
def get_mouse_clicked_count(button: int) -> int: ...
def get_mouse_cursor() -> int: ...
def get_mouse_drag_delta(pOut: _ImVec2, button: int=0, lock_threshold: float=-1.0) -> None: ...
def get_mouse_pos(pOut: _ImVec2) -> None: ...
def get_mouse_pos_on_opening_current_popup(pOut: _ImVec2) -> None: ...
def get_platform_io() -> _ImGuiPlatformIO: ...
def get_scroll_maxx() -> float: ...
def get_scroll_maxy() -> float: ...
def get_scrollx() -> float: ...
def get_scrolly() -> float: ...
def get_state_storage() -> _ImGuiStorage: ...
def get_style() -> _ImGuiStyle: ...
def get_style_color_name(idx: int) -> str: ...
def get_style_color_vec4(idx: int) -> _ImVec4: ...
def get_text_line_height() -> float: ...
def get_text_line_height_with_spacing() -> float: ...
def get_time() -> float: ...
def get_tree_node_to_label_spacing() -> float: ...
def get_version() -> str: ...
def get_window_content_region_max(pOut: _ImVec2) -> None: ...
def get_window_content_region_min(pOut: _ImVec2) -> None: ...
def get_window_dock_id() -> int: ...
def get_window_dpi_scale() -> float: ...
def get_window_draw_list() -> _ImDrawList: ...
def get_window_height() -> float: ...
def get_window_pos(pOut: _ImVec2) -> None: ...
def get_window_size(pOut: _ImVec2) -> None: ...
def get_window_viewport() -> _ImGuiViewport: ...
def get_window_width() -> float: ...
def image(user_texture_id: Any, size: tuple, uv0: tuple=(0, 0), uv1: tuple=(1, 1), tint_col: tuple=(1, 1, 1, 1), border_col: tuple=(0, 0, 0, 0)) -> None: ...
def image_button(str_id: str, user_texture_id: Any, size: tuple, uv0: tuple=(0, 0), uv1: tuple=(1, 1), bg_col: tuple=(0, 0, 0, 0), tint_col: tuple=(1, 1, 1, 1)) -> Any: ...
def indent(indent_w: float=0.0) -> None: ...
def input_double(label: str, value: Any, step: float=0.0, step_fast: float=0.0, format_: str="%.6", flags: int=0) -> Any: ...
def input_float(label: str, value: float, step: float=0.0, step_fast: float=0.0, format_: str="%.3", flags: int=0) -> Any: ...
def input_float2(label: str, value0: float, value1: float, format_: str="%.3", flags: int=0) -> Any: ...
def input_float3(label: str, value0: float, value1: float, value2: float, format_: str="%.3", flags: int=0) -> Any: ...
def input_float4(label: str, value0: float, value1: float, value2: float, value3: float, format_: str="%.3", flags: int=0) -> Any: ...
def input_int(label: str, value: int, step: int=1, step_fast: int=100, flags: int=0) -> Any: ...
def input_int2(label: str, value0: int, value1: int, flags: int=0) -> Any: ...
def input_int3(label: str, value0: int, value1: int, value2: int, flags: int=0) -> Any: ...
def input_int4(label: str, value0: int, value1: int, value2: int, value3: int, flags: int=0) -> Any: ...
def input_scalar(label: str, data_type: int, p_data: Any, p_step: Any=None, p_step_fast: Any=None, format_: str=None, flags: int=0) -> Any: ...
def input_scalarn(label: str, data_type: int, p_data: Any, components: int, p_step: Any=None, p_step_fast: Any=None, format_: str=None, flags: int=0) -> Any: ...
def invisible_button(str_id: str, size: tuple, flags: int=0) -> Any: ...
def is_any_item_active() -> Any: ...
def is_any_item_focused() -> Any: ...
def is_any_item_hovered() -> Any: ...
def is_any_mouse_down() -> Any: ...
def is_item_activated() -> Any: ...
def is_item_active() -> Any: ...
def is_item_clicked(mouse_button: int=0) -> Any: ...
def is_item_deactivated() -> Any: ...
def is_item_deactivated_after_edit() -> Any: ...
def is_item_edited() -> Any: ...
def is_item_focused() -> Any: ...
def is_item_hovered(flags: int=0) -> Any: ...
def is_item_toggled_open() -> Any: ...
def is_item_visible() -> Any: ...
def is_key_down(key: Any) -> Any: ...
def is_key_pressed(key: Any, repeat: Any=True) -> Any: ...
def is_key_released(key: Any) -> Any: ...
def is_mouse_clicked(button: int, repeat: Any=False) -> Any: ...
def is_mouse_double_clicked(button: int) -> Any: ...
def is_mouse_down(button: int) -> Any: ...
def is_mouse_dragging(button: int, lock_threshold: float=-1.0) -> Any: ...
def is_mouse_hovering_rect(r_min: tuple, r_max: tuple, clip: Any=True) -> Any: ...
def is_mouse_pos_valid(mouse_pos: _ImVec2=None) -> Any: ...
def is_mouse_released(button: int) -> Any: ...
def is_popup_open(str_id: str, flags: int=0) -> Any: ...
def is_rect_visible_nil(size: tuple) -> Any: ...
def is_rect_visible_vec2(rect_min: tuple, rect_max: tuple) -> Any: ...
def is_window_appearing() -> Any: ...
def is_window_collapsed() -> Any: ...
def is_window_docked() -> Any: ...
def is_window_focused(flags: int=0) -> Any: ...
def is_window_hovered(flags: int=0) -> Any: ...
def label_text(label: str, fmt: str) -> None: ...
def label_textv(label: str, fmt: str, args: str) -> None: ...
def list_box_fn_bool_ptr(label: str, current_item: int, items_getter: Callable, data: Any, items_count: int, height_in_items: int=-1) -> Any: ...
def list_box_str_arr(label: str, current_item: int, items: Any, items_count: int, height_in_items: int=-1) -> Any: ...
def load_ini_settings_from_disk(ini_filename: str) -> None: ...
def load_ini_settings_from_memory(ini_data: str, ini_size: Any=0) -> None: ...
def log_buttons() -> None: ...
def log_finish() -> None: ...
def log_text(fmt: str) -> None: ...
def log_textv(fmt: str, args: str) -> None: ...
def log_to_clipboard(auto_open_depth: int=-1) -> None: ...
def log_to_file(auto_open_depth: int=-1, filename: str=None) -> None: ...
def log_to_tty(auto_open_depth: int=-1) -> None: ...
def mem_alloc(size: Any) -> Any: ...
def mem_free(ptr: Any) -> None: ...
def menu_item_bool(label: str, shortcut: str=None, selected: Any=False, enabled: Any=True) -> Any: ...
def menu_item_bool_ptr(label: str, shortcut: str, p_selected: Any, enabled: Any=True) -> Any: ...
def new_frame() -> None: ...
def new_line() -> None: ...
def next_column() -> None: ...
def open_popup_id(id_: int, popup_flags: int=0) -> None: ...
def open_popup_on_item_click(str_id: str=None, popup_flags: int=1) -> None: ...
def open_popup_str(str_id: str, popup_flags: int=0) -> None: ...
def plot_histogram_float_ptr(label: str, values: float, values_count: int, values_offset: int=0, overlay_text: str=None, scale_min: float=FLT_MAX, scale_max: float=FLT_MAX, graph_size: tuple=(0, 0), stride: int=sizeof(float)) -> None: ...
def plot_histogram_fn_float_ptr(label: str, values_getter: Callable, data: Any, values_count: int, values_offset: int=0, overlay_text: str=None, scale_min: float=FLT_MAX, scale_max: float=FLT_MAX, graph_size: tuple=(0, 0)) -> None: ...
def plot_lines_float_ptr(label: str, values: float, values_count: int, values_offset: int=0, overlay_text: str=None, scale_min: float=FLT_MAX, scale_max: float=FLT_MAX, graph_size: tuple=(0, 0), stride: int=sizeof(float)) -> None: ...
def plot_lines_fn_float_ptr(label: str, values_getter: Callable, data: Any, values_count: int, values_offset: int=0, overlay_text: str=None, scale_min: float=FLT_MAX, scale_max: float=FLT_MAX, graph_size: tuple=(0, 0)) -> None: ...
def pop_allow_keyboard_focus() -> None: ...
def pop_button_repeat() -> None: ...
def pop_clip_rect() -> None: ...
def pop_font() -> None: ...
def pop_id() -> None: ...
def pop_item_width() -> None: ...
def pop_style_color(count: int=1) -> None: ...
def pop_style_var(count: int=1) -> None: ...
def pop_text_wrap_pos() -> None: ...
def progress_bar(fraction: float, size_arg: tuple=(-FLT_MIN, 0), overlay: str=None) -> None: ...
def push_allow_keyboard_focus(allow_keyboard_focus: Any) -> None: ...
def push_button_repeat(repeat: Any) -> None: ...
def push_clip_rect(clip_rect_min: tuple, clip_rect_max: tuple, intersect_with_current_clip_rect: Any) -> None: ...
def push_font(font: _ImFont) -> None: ...
def push_id_int(int_id: int) -> None: ...
def push_id_ptr(ptr_id: Any) -> None: ...
def push_id_str(str_id: str) -> None: ...
def push_id_str_str(str_id_begin: str, str_id_end: str) -> None: ...
def push_item_width(item_width: float) -> None: ...
def push_style_color_u32(idx: int, col: int) -> None: ...
def push_style_color_vec4(idx: int, col: tuple) -> None: ...
def push_style_var_float(idx: int, val: float) -> None: ...
def push_style_var_vec2(idx: int, val: tuple) -> None: ...
def push_text_wrap_pos(wrap_local_pos_x: float=0.0) -> None: ...
def radio_button_bool(label: str, active: Any) -> Any: ...
def radio_button_int_ptr(label: str, value: int, v_button: int) -> Any: ...
def render() -> None: ...
def render_platform_windows_default(platform_render_arg: Any=None, renderer_render_arg: Any=None) -> None: ...
def reset_mouse_drag_delta(button: int=0) -> None: ...
def same_line(offset_from_start_x: float=0.0, spacing: float=-1.0) -> None: ...
def save_ini_settings_to_disk(ini_filename: str) -> None: ...
def save_ini_settings_to_memory(out_ini_size: Any=None) -> str: ...
def selectable_bool(label: str, selected: Any=False, flags: int=0, size: tuple=(0, 0)) -> Any: ...
def selectable_bool_ptr(label: str, p_selected: Any, flags: int=0, size: tuple=(0, 0)) -> Any: ...
def separator() -> None: ...
def separator_text(label: str) -> None: ...
def set_clipboard_text(text: str) -> None: ...
def set_color_edit_options(flags: int) -> None: ...
def set_column_offset(column_index: int, offset_x: float) -> None: ...
def set_column_width(column_index: int, width: float) -> None: ...
def set_current_context(ctx: _ImGuiContext) -> None: ...
def set_cursor_pos(local_pos: tuple) -> None: ...
def set_cursor_posx(local_x: float) -> None: ...
def set_cursor_posy(local_y: float) -> None: ...
def set_cursor_screen_pos(pos: tuple) -> None: ...
def set_drag_drop_payload(type_: str, data: Any, sz: Any, cond: int=0) -> Any: ...
def set_item_allow_overlap() -> None: ...
def set_item_default_focus() -> None: ...
def set_keyboard_focus_here(offset: int=0) -> None: ...
def set_mouse_cursor(cursor_type: int) -> None: ...
def set_next_frame_want_capture_keyboard(want_capture_keyboard: Any) -> None: ...
def set_next_frame_want_capture_mouse(want_capture_mouse: Any) -> None: ...
def set_next_item_open(is_open: Any, cond: int=0) -> None: ...
def set_next_item_width(item_width: float) -> None: ...
def set_next_window_bg_alpha(alpha: float) -> None: ...
def set_next_window_class(window_class: _ImGuiWindowClass) -> None: ...
def set_next_window_collapsed(collapsed: Any, cond: int=0) -> None: ...
def set_next_window_content_size(size: tuple) -> None: ...
def set_next_window_dock_id(dock_id: int, cond: int=0) -> None: ...
def set_next_window_focus() -> None: ...
def set_next_window_pos(pos: tuple, cond: int=0, pivot: tuple=(0, 0)) -> None: ...
def set_next_window_scroll(scroll: tuple) -> None: ...
def set_next_window_size(size: tuple, cond: int=0) -> None: ...
def set_next_window_viewport(viewport_id: int) -> None: ...
def set_scroll_from_posx(local_x: float, center_x_ratio: float=0.5) -> None: ...
def set_scroll_from_posy(local_y: float, center_y_ratio: float=0.5) -> None: ...
def set_scroll_herex(center_x_ratio: float=0.5) -> None: ...
def set_scroll_herey(center_y_ratio: float=0.5) -> None: ...
def set_scrollx(scroll_x: float) -> None: ...
def set_scrolly(scroll_y: float) -> None: ...
def set_state_storage(storage: _ImGuiStorage) -> None: ...
def set_tab_item_closed(tab_or_docked_window_label: str) -> None: ...
def set_tooltip(fmt: str) -> None: ...
def set_tooltipv(fmt: str, args: str) -> None: ...
def set_window_collapsed_bool(collapsed: Any, cond: int=0) -> None: ...
def set_window_collapsed_str(name: str, collapsed: Any, cond: int=0) -> None: ...
def set_window_focus_nil() -> None: ...
def set_window_focus_str(name: str) -> None: ...
def set_window_font_scale(scale: float) -> None: ...
def set_window_pos_str(name: str, pos: tuple, cond: int=0) -> None: ...
def set_window_pos_vec2(pos: tuple, cond: int=0) -> None: ...
def set_window_size_str(name: str, size: tuple, cond: int=0) -> None: ...
def set_window_size_vec2(size: tuple, cond: int=0) -> None: ...
def show_about_window(p_open: Any=None) -> None: ...
def show_debug_log_window(p_open: Any=None) -> None: ...
def show_demo_window(closable: bool=False) -> None: ...
def show_font_selector(label: str) -> None: ...
def show_metrics_window(p_open: Any=None) -> None: ...
def show_stack_tool_window(p_open: Any=None) -> None: ...
def show_style_editor(ref: _ImGuiStyle=None) -> None: ...
def show_style_selector(label: str) -> Any: ...
def show_user_guide() -> None: ...
def slider_angle(label: str, v_rad: float, v_degrees_min: float=-360.0, v_degrees_max: float=+360.0, format_: str="%.0 deg", flags: int=0) -> Any: ...
def slider_float(label: str, value: float, v_min: float, v_max: float, format_: str="%.3", flags: int=0) -> Any: ...
def slider_float2(label: str, value0: float, value1: float, v_min: float, v_max: float, format_: str="%.3", flags: int=0) -> Any: ...
def slider_float3(label: str, value0: float, value1: float, value2: float, v_min: float, v_max: float, format_: str="%.3", flags: int=0) -> Any: ...
def slider_float4(label: str, value0: float, value1: float, value2: float, value3: float, v_min: float, v_max: float, format_: str="%.3", flags: int=0) -> Any: ...
def slider_int(label: str, value: int, v_min: int, v_max: int, format_: str="%d", flags: int=0) -> Any: ...
def slider_int2(label: str, value0: int, value1: int, v_min: int, v_max: int, format_: str="%d", flags: int=0) -> Any: ...
def slider_int3(label: str, value0: int, value1: int, value2: int, v_min: int, v_max: int, format_: str="%d", flags: int=0) -> Any: ...
def slider_int4(label: str, value0: int, value1: int, value2: int, value3: int, v_min: int, v_max: int, format_: str="%d", flags: int=0) -> Any: ...
def slider_scalar(label: str, data_type: int, p_data: Any, p_min: Any, p_max: Any, format_: str=None, flags: int=0) -> Any: ...
def slider_scalarn(label: str, data_type: int, p_data: Any, components: int, p_min: Any, p_max: Any, format_: str=None, flags: int=0) -> Any: ...
def small_button(label: str) -> Any: ...
def spacing() -> None: ...
def style_colors_classic(dst: _ImGuiStyle=None) -> None: ...
def style_colors_dark(dst: _ImGuiStyle=None) -> None: ...
def style_colors_light(dst: _ImGuiStyle=None) -> None: ...
def tab_item_button(label: str, flags: int=0) -> Any: ...
def table_get_column_count() -> int: ...
def table_get_column_flags(column_n: int=-1) -> int: ...
def table_get_column_index() -> int: ...
def table_get_column_name(column_n: int=-1) -> str: ...
def table_get_row_index() -> int: ...
def table_get_sort_specs() -> _ImGuiTableSortSpecs: ...
def table_header(label: str) -> None: ...
def table_headers_row() -> None: ...
def table_next_column() -> Any: ...
def table_next_row(row_flags: int=0, min_row_height: float=0.0) -> None: ...
def table_set_bg_color(target: int, color: int, column_n: int=-1) -> None: ...
def table_set_column_enabled(column_n: int, value: Any) -> None: ...
def table_set_column_index(column_n: int) -> Any: ...
def table_setup_column(label: str, flags: int=0, init_width_or_weight: float=0.0, user_id: int=0) -> None: ...
def table_setup_scroll_freeze(cols: int, rows: int) -> None: ...
def text(fmt: str) -> None: ...
def text_colored(col: tuple, fmt: str) -> None: ...
def text_coloredv(col: tuple, fmt: str, args: str) -> None: ...
def text_disabled(fmt: str) -> None: ...
def text_disabledv(fmt: str, args: str) -> None: ...
def text_unformatted(text: str, text_end: str=None) -> None: ...
def text_wrapped(fmt: str) -> None: ...
def text_wrappedv(fmt: str, args: str) -> None: ...
def textv(fmt: str, args: str) -> None: ...
def tree_node_ex_ptr(ptr_id: Any, flags: int, fmt: str) -> Any: ...
def tree_node_ex_str(label: str, flags: int=0) -> Any: ...
def tree_node_ex_str_str(str_id: str, flags: int, fmt: str) -> Any: ...
def tree_node_ex_v_ptr(ptr_id: Any, flags: int, fmt: str, args: str) -> Any: ...
def tree_node_ex_v_str(str_id: str, flags: int, fmt: str, args: str) -> Any: ...
def tree_node_ptr(ptr_id: Any, fmt: str) -> Any: ...
def tree_node_str(label: str) -> Any: ...
def tree_node_str_str(str_id: str, fmt: str) -> Any: ...
def tree_node_v_ptr(ptr_id: Any, fmt: str, args: str) -> Any: ...
def tree_node_v_str(str_id: str, fmt: str, args: str) -> Any: ...
def tree_pop() -> None: ...
def tree_push_ptr(ptr_id: Any) -> None: ...
def tree_push_str(str_id: str) -> None: ...
def unindent(indent_w: float=0.0) -> None: ...
def update_platform_windows() -> None: ...
def v_slider_float(label: str, size: tuple, value: float, v_min: float, v_max: float, format_: str="%.3", flags: int=0) -> Any: ...
def v_slider_int(label: str, size: tuple, value: int, v_min: int, v_max: int, format_: str="%d", flags: int=0) -> Any: ...
def v_slider_scalar(label: str, size: tuple, data_type: int, p_data: Any, p_min: Any, p_max: Any, format_: str=None, flags: int=0) -> Any: ...
def value_bool(prefix: str, b: Any) -> None: ...
def value_float(prefix: str, value: float, float_format: str=None) -> None: ...
def value_int(prefix: str, value: int) -> None: ...
def value_uint(prefix: str, value: int) -> None: ...

class _ImColor:
    value: tuple
    def destroy(self: _ImColor) -> None: ...
    def float_(r: float, g: float, b: float, a: float=1.0) -> _ImColor: ...
    def hsv(pOut: _ImColor, h: float, s: float, value: float, a: float=1.0) -> None: ...
    def int_(r: int, g: int, b: int, a: int=255) -> _ImColor: ...
    def nil() -> _ImColor: ...
    def set_hsv(self: _ImColor, h: float, s: float, value: float, a: float=1.0) -> None: ...
    def u32(rgba: int) -> _ImColor: ...
    def vec4(col: tuple) -> _ImColor: ...

class _ImDrawChannel:
    _cmd_buffer: _ImVector_ImDrawCmd
    _idx_buffer: _ImVector_ImDrawIdx

class _ImDrawCmd:
    clip_rect: tuple
    elem_count: int
    idx_offset: int
    texture_id: Any
    user_callback_data: Any
    vtx_offset: int
    def destroy(self: _ImDrawCmd) -> None: ...
    def draw_cmd() -> _ImDrawCmd: ...
    def get_tex_id(self: _ImDrawCmd) -> Any: ...

class _ImDrawCmdHeader:
    clip_rect: tuple
    texture_id: Any
    vtx_offset: int

class _ImDrawData:
    cmd_lists: _ImDrawList
    cmd_lists_count: int
    display_pos: tuple
    display_size: tuple
    framebuffer_scale: tuple
    owner_viewport: _ImGuiViewport
    total_idx_count: int
    total_vtx_count: int
    valid: Any
    def clear(self: _ImDrawData) -> None: ...
    def de_index_all_buffers(self: _ImDrawData) -> None: ...
    def destroy(self: _ImDrawData) -> None: ...
    def draw_data() -> _ImDrawData: ...
    def scale_clip_rects(self: _ImDrawData, fb_scale: tuple) -> None: ...

class _ImDrawList:
    _clip_rect_stack: _ImVector_ImVec4
    _cmd_header: _ImDrawCmdHeader
    _data: _ImDrawListSharedData
    _fringe_scale: float
    _idx_write_ptr: int
    _owner_name: str
    _path: _ImVector_ImVec2
    _splitter: _ImDrawListSplitter
    _texture_id_stack: _ImVector_ImTextureID
    _vtx_current_idx: int
    _vtx_write_ptr: _ImDrawVert
    cmd_buffer: _ImVector_ImDrawCmd
    flags: int
    idx_buffer: _ImVector_ImDrawIdx
    vtx_buffer: _ImVector_ImDrawVert
    def _calc_circle_auto_segment_count(self: _ImDrawList, radius: float) -> int: ...
    def _clear_free_memory(self: _ImDrawList) -> None: ...
    def _on_changed_clip_rect(self: _ImDrawList) -> None: ...
    def _on_changed_texture_id(self: _ImDrawList) -> None: ...
    def _on_changed_vtx_offset(self: _ImDrawList) -> None: ...
    def _path_arc_to_fast_ex(self: _ImDrawList, center: tuple, radius: float, a_min_sample: int, a_max_sample: int, a_step: int) -> None: ...
    def _path_arc_ton(self: _ImDrawList, center: tuple, radius: float, a_min: float, a_max: float, num_segments: int) -> None: ...
    def _pop_unused_draw_cmd(self: _ImDrawList) -> None: ...
    def _reset_for_new_frame(self: _ImDrawList) -> None: ...
    def _try_merge_draw_cmds(self: _ImDrawList) -> None: ...
    def add_bezier_cubic(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, p4: tuple, col: int, thickness: float, num_segments: int=0) -> None: ...
    def add_bezier_quadratic(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, col: int, thickness: float, num_segments: int=0) -> None: ...
    def add_circle(self: _ImDrawList, center: tuple, radius: float, col: int, num_segments: int=0, thickness: float=1.0) -> None: ...
    def add_circle_filled(self: _ImDrawList, center: tuple, radius: float, col: int, num_segments: int=0) -> None: ...
    def add_convex_poly_filled(self: _ImDrawList, points: _ImVec2, num_points: int, col: int) -> None: ...
    def add_draw_cmd(self: _ImDrawList) -> None: ...
    def add_image(self: _ImDrawList, user_texture_id: Any, p_min: tuple, p_max: tuple, uv_min: tuple=(0, 0), uv_max: tuple=(1, 1), col: int=4294967295) -> None: ...
    def add_image_quad(self: _ImDrawList, user_texture_id: Any, p1: tuple, p2: tuple, p3: tuple, p4: tuple, uv1: tuple=(0, 0), uv2: tuple=(1, 0), uv3: tuple=(1, 1), uv4: tuple=(0, 1), col: int=4294967295) -> None: ...
    def add_image_rounded(self: _ImDrawList, user_texture_id: Any, p_min: tuple, p_max: tuple, uv_min: tuple, uv_max: tuple, col: int, rounding: float, flags: int=0) -> None: ...
    def add_line(self: _ImDrawList, p1: tuple, p2: tuple, col: int, thickness: float=1.0) -> None: ...
    def add_ngon(self: _ImDrawList, center: tuple, radius: float, col: int, num_segments: int, thickness: float=1.0) -> None: ...
    def add_ngon_filled(self: _ImDrawList, center: tuple, radius: float, col: int, num_segments: int) -> None: ...
    def add_polyline(self: _ImDrawList, points: _ImVec2, num_points: int, col: int, flags: int, thickness: float) -> None: ...
    def add_quad(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, p4: tuple, col: int, thickness: float=1.0) -> None: ...
    def add_quad_filled(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, p4: tuple, col: int) -> None: ...
    def add_rect(self: _ImDrawList, p_min: tuple, p_max: tuple, col: int, rounding: float=0.0, flags: int=0, thickness: float=1.0) -> None: ...
    def add_rect_filled(self: _ImDrawList, p_min: tuple, p_max: tuple, col: int, rounding: float=0.0, flags: int=0) -> None: ...
    def add_rect_filled_multi_color(self: _ImDrawList, p_min: tuple, p_max: tuple, col_upr_left: int, col_upr_right: int, col_bot_right: int, col_bot_left: int) -> None: ...
    def add_text_font_ptr(self: _ImDrawList, font: _ImFont, font_size: float, pos: tuple, col: int, text_begin: str, text_end: str=None, wrap_width: float=0.0, cpu_fine_clip_rect: _ImVec4=None) -> None: ...
    def add_text_vec2(self: _ImDrawList, pos: tuple, col: int, text_begin: str, text_end: str=None) -> None: ...
    def add_triangle(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, col: int, thickness: float=1.0) -> None: ...
    def add_triangle_filled(self: _ImDrawList, p1: tuple, p2: tuple, p3: tuple, col: int) -> None: ...
    def channels_merge(self: _ImDrawList) -> None: ...
    def channels_set_current(self: _ImDrawList, n: int) -> None: ...
    def channels_split(self: _ImDrawList, count: int) -> None: ...
    def clone_output(self: _ImDrawList) -> _ImDrawList: ...
    def destroy(self: _ImDrawList) -> None: ...
    def draw_list(shared_data: _ImDrawListSharedData) -> _ImDrawList: ...
    def get_clip_rect_max(pOut: _ImVec2, self: _ImDrawList) -> None: ...
    def get_clip_rect_min(pOut: _ImVec2, self: _ImDrawList) -> None: ...
    def path_arc_to(self: _ImDrawList, center: tuple, radius: float, a_min: float, a_max: float, num_segments: int=0) -> None: ...
    def path_arc_to_fast(self: _ImDrawList, center: tuple, radius: float, a_min_of_12: int, a_max_of_12: int) -> None: ...
    def path_bezier_cubic_curve_to(self: _ImDrawList, p2: tuple, p3: tuple, p4: tuple, num_segments: int=0) -> None: ...
    def path_bezier_quadratic_curve_to(self: _ImDrawList, p2: tuple, p3: tuple, num_segments: int=0) -> None: ...
    def path_clear(self: _ImDrawList) -> None: ...
    def path_fill_convex(self: _ImDrawList, col: int) -> None: ...
    def path_line_to(self: _ImDrawList, pos: tuple) -> None: ...
    def path_line_to_merge_duplicate(self: _ImDrawList, pos: tuple) -> None: ...
    def path_rect(self: _ImDrawList, rect_min: tuple, rect_max: tuple, rounding: float=0.0, flags: int=0) -> None: ...
    def path_stroke(self: _ImDrawList, col: int, flags: int=0, thickness: float=1.0) -> None: ...
    def pop_clip_rect(self: _ImDrawList) -> None: ...
    def pop_texture_id(self: _ImDrawList) -> None: ...
    def prim_quad_uv(self: _ImDrawList, a: tuple, b: tuple, c: tuple, d: tuple, uv_a: tuple, uv_b: tuple, uv_c: tuple, uv_d: tuple, col: int) -> None: ...
    def prim_rect(self: _ImDrawList, a: tuple, b: tuple, col: int) -> None: ...
    def prim_rect_uv(self: _ImDrawList, a: tuple, b: tuple, uv_a: tuple, uv_b: tuple, col: int) -> None: ...
    def prim_reserve(self: _ImDrawList, idx_count: int, vtx_count: int) -> None: ...
    def prim_unreserve(self: _ImDrawList, idx_count: int, vtx_count: int) -> None: ...
    def prim_vtx(self: _ImDrawList, pos: tuple, uv: tuple, col: int) -> None: ...
    def prim_write_idx(self: _ImDrawList, idx: int) -> None: ...
    def prim_write_vtx(self: _ImDrawList, pos: tuple, uv: tuple, col: int) -> None: ...
    def push_clip_rect(self: _ImDrawList, clip_rect_min: tuple, clip_rect_max: tuple, intersect_with_current_clip_rect: Any=False) -> None: ...
    def push_clip_rect_full_screen(self: _ImDrawList) -> None: ...
    def push_texture_id(self: _ImDrawList, texture_id: Any) -> None: ...

class _ImDrawListSharedData: ...
class _ImDrawListSplitter:
    _channels: _ImVector_ImDrawChannel
    _count: int
    _current: int
    def clear(self: _ImDrawListSplitter) -> None: ...
    def clear_free_memory(self: _ImDrawListSplitter) -> None: ...
    def destroy(self: _ImDrawListSplitter) -> None: ...
    def draw_list_splitter() -> _ImDrawListSplitter: ...
    def merge(self: _ImDrawListSplitter, draw_list: _ImDrawList) -> None: ...
    def set_current_channel(self: _ImDrawListSplitter, draw_list: _ImDrawList, channel_idx: int) -> None: ...
    def split(self: _ImDrawListSplitter, draw_list: _ImDrawList, count: int) -> None: ...

class _ImDrawVert:
    col: int
    pos: tuple
    uv: tuple

class _ImFont:
    ascent: float
    config_data: _ImFontConfig
    config_data_count: int
    container_atlas: _ImFontAtlas
    descent: float
    dirty_lookup_tables: Any
    ellipsis_char: int
    ellipsis_char_count: int
    ellipsis_char_step: float
    ellipsis_width: float
    fallback_advancex: float
    fallback_char: int
    fallback_glyph: _ImFontGlyph
    font_size: float
    glyphs: _ImVector_ImFontGlyph
    index_advancex: _ImVector_float
    index_lookup: _ImVector_ImWchar
    metrics_total_surface: int
    scale: float
    used_4k_pages_map: int
    def add_glyph(self: _ImFont, src_cfg: _ImFontConfig, c: int, x0: float, y0: float, x1: float, y1: float, u0: float, v0: float, u1: float, v1: float, advance_x: float) -> None: ...
    def add_remap_char(self: _ImFont, dst: int, src: int, overwrite_dst: Any=True) -> None: ...
    def build_lookup_table(self: _ImFont) -> None: ...
    def calc_text_sizea(pOut: _ImVec2, self: _ImFont, size: float, max_width: float, wrap_width: float, text_begin: str, text_end: str=None, remaining: Any=None) -> None: ...
    def calc_word_wrap_positiona(self: _ImFont, scale: float, text: str, text_end: str, wrap_width: float) -> str: ...
    def clear_output_data(self: _ImFont) -> None: ...
    def destroy(self: _ImFont) -> None: ...
    def find_glyph(self: _ImFont, c: int) -> _ImFontGlyph: ...
    def find_glyph_no_fallback(self: _ImFont, c: int) -> _ImFontGlyph: ...
    def font() -> _ImFont: ...
    def get_char_advance(self: _ImFont, c: int) -> float: ...
    def get_debug_name(self: _ImFont) -> str: ...
    def grow_index(self: _ImFont, new_size: int) -> None: ...
    def is_glyph_range_unused(self: _ImFont, c_begin: int, c_last: int) -> Any: ...
    def is_loaded(self: _ImFont) -> Any: ...
    def render_char(self: _ImFont, draw_list: _ImDrawList, size: float, pos: tuple, col: int, c: int) -> None: ...
    def render_text(self: _ImFont, draw_list: _ImDrawList, size: float, pos: tuple, col: int, clip_rect: tuple, text_begin: str, text_end: str, wrap_width: float=0.0, cpu_fine_clip: Any=False) -> None: ...
    def set_glyph_visible(self: _ImFont, c: int, visible: Any) -> None: ...

class _ImFontAtlas:
    config_data: _ImVector_ImFontConfig
    custom_rects: _ImVector_ImFontAtlasCustomRect
    flags: int
    font_builder_flags: int
    font_builder_io: _ImFontBuilderIO
    fonts: _ImVector_ImFontPtr
    locked: Any
    pack_id_lines: int
    pack_id_mouse_cursors: int
    tex_desired_width: int
    tex_glyph_padding: int
    tex_height: int
    tex_id: Any
    tex_pixels_alpha8: str
    tex_pixels_rgba32: int
    tex_pixels_use_colors: Any
    tex_ready: Any
    tex_uv_lines: tuple
    tex_uv_scale: tuple
    tex_uv_white_pixel: tuple
    tex_width: int
    user_data: Any
    def add_custom_rect_font_glyph(self: _ImFontAtlas, font: _ImFont, id_: int, width: int, height: int, advance_x: float, offset: tuple=(0, 0)) -> int: ...
    def add_custom_rect_regular(self: _ImFontAtlas, width: int, height: int) -> int: ...
    def add_font(self: _ImFontAtlas, font_cfg: _ImFontConfig) -> _ImFont: ...
    def add_font_default(self: _ImFontAtlas, font_cfg: _ImFontConfig=None) -> _ImFont: ...
    def add_font_from_file_ttf(self: _ImFontAtlas, filename: str, size_pixels: float, font_cfg: _ImFontConfig=None, glyph_ranges: int=None) -> _ImFont: ...
    def add_font_from_memory_compressed_base_85ttf(self: _ImFontAtlas, compressed_font_data_base85: str, size_pixels: float, font_cfg: _ImFontConfig=None, glyph_ranges: int=None) -> _ImFont: ...
    def add_font_from_memory_compressed_ttf(self: _ImFontAtlas, compressed_font_data: Any, compressed_font_size: int, size_pixels: float, font_cfg: _ImFontConfig=None, glyph_ranges: int=None) -> _ImFont: ...
    def add_font_from_memory_ttf(self: _ImFontAtlas, font_data: Any, font_size: int, size_pixels: float, font_cfg: _ImFontConfig=None, glyph_ranges: int=None) -> _ImFont: ...
    def build(self: _ImFontAtlas) -> Any: ...
    def calc_custom_rect_uv(self: _ImFontAtlas, rect: _ImFontAtlasCustomRect, out_uv_min: _ImVec2, out_uv_max: _ImVec2) -> None: ...
    def clear(self: _ImFontAtlas) -> None: ...
    def clear_fonts(self: _ImFontAtlas) -> None: ...
    def clear_input_data(self: _ImFontAtlas) -> None: ...
    def clear_tex_data(self: _ImFontAtlas) -> None: ...
    def destroy(self: _ImFontAtlas) -> None: ...
    def font_atlas() -> _ImFontAtlas: ...
    def get_custom_rect_by_index(self: _ImFontAtlas, index: int) -> _ImFontAtlasCustomRect: ...
    def get_glyph_ranges_chinese_full(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_chinese_simplified_common(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_cyrillic(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_default(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_greek(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_japanese(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_korean(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_thai(self: _ImFontAtlas) -> int: ...
    def get_glyph_ranges_vietnamese(self: _ImFontAtlas) -> int: ...
    def get_mouse_cursor_tex_data(self: _ImFontAtlas, cursor: int, out_offset: _ImVec2, out_size: _ImVec2, out_uv_border0: tuple, out_uv_border1: tuple, out_uv_fill0: tuple, out_uv_fill1: tuple) -> Any: ...
    def get_tex_data_as_alpha8(self: _ImFontAtlas, out_pixels: Any, out_width: int, out_height: int, out_bytes_per_pixel: int=None) -> None: ...
    def get_tex_data_as_rgba32(self: _ImFontAtlas, out_pixels: Any, out_width: int, out_height: int, out_bytes_per_pixel: int=None) -> None: ...
    def is_built(self: _ImFontAtlas) -> Any: ...
    def set_tex_id(self: _ImFontAtlas, id_: Any) -> None: ...

class _ImFontAtlasCustomRect:
    font: _ImFont
    glyph_advancex: float
    glyph_id: int
    glyph_offset: tuple
    height: int
    width: int
    x: int
    y: int
    def destroy(self: _ImFontAtlasCustomRect) -> None: ...
    def font_atlas_custom_rect() -> _ImFontAtlasCustomRect: ...
    def is_packed(self: _ImFontAtlasCustomRect) -> Any: ...

class _ImFontBuilderIO: ...
class _ImFontConfig:
    dst_font: _ImFont
    ellipsis_char: int
    font_builder_flags: int
    font_data: Any
    font_data_owned_by_atlas: Any
    font_data_size: int
    font_no: int
    glyph_extra_spacing: tuple
    glyph_max_advancex: float
    glyph_min_advancex: float
    glyph_offset: tuple
    glyph_ranges: int
    merge_mode: Any
    name: int
    oversampleh: int
    oversamplev: int
    pixel_snaph: Any
    rasterizer_multiply: float
    size_pixels: float
    def destroy(self: _ImFontConfig) -> None: ...
    def font_config() -> _ImFontConfig: ...

class _ImFontGlyph:
    advancex: float
    codepoint: int
    colored: int
    u0: float
    u1: float
    v0: float
    v1: float
    visible: int
    x0: float
    x1: float
    y0: float
    y1: float

class _ImFontGlyphRangesBuilder:
    used_chars: _ImVector_ImU32
    def add_char(self: _ImFontGlyphRangesBuilder, c: int) -> None: ...
    def add_ranges(self: _ImFontGlyphRangesBuilder, ranges: int) -> None: ...
    def add_text(self: _ImFontGlyphRangesBuilder, text: str, text_end: str=None) -> None: ...
    def build_ranges(self: _ImFontGlyphRangesBuilder, out_ranges: _ImVector_ImWchar) -> None: ...
    def clear(self: _ImFontGlyphRangesBuilder) -> None: ...
    def destroy(self: _ImFontGlyphRangesBuilder) -> None: ...
    def font_glyph_ranges_builder() -> _ImFontGlyphRangesBuilder: ...
    def get_bit(self: _ImFontGlyphRangesBuilder, n: Any) -> Any: ...
    def set_bit(self: _ImFontGlyphRangesBuilder, n: Any) -> None: ...

class _ImGuiContext: ...
class _ImGuiIO:
    _unused_padding: Any
    app_accepting_events: Any
    app_focus_lost: Any
    backend_flags: int
    backend_language_user_data: Any
    backend_platform_name: str
    backend_platform_user_data: Any
    backend_renderer_name: str
    backend_renderer_user_data: Any
    backend_using_legacy_key_arrays: int
    backend_using_legacy_nav_input_array: Any
    clipboard_user_data: Any
    config_docking_always_tab_bar: Any
    config_docking_no_split: Any
    config_docking_transparent_payload: Any
    config_docking_with_shift: Any
    config_drag_click_to_input_text: Any
    config_flags: int
    config_input_text_cursor_blink: Any
    config_input_text_enter_keep_active: Any
    config_input_trickle_event_queue: Any
    config_mac_osx_behaviors: Any
    config_memory_compact_timer: float
    config_viewports_no_auto_merge: Any
    config_viewports_no_decoration: Any
    config_viewports_no_default_parent: Any
    config_viewports_no_task_bar_icon: Any
    config_windows_move_from_title_bar_only: Any
    config_windows_resize_from_edges: Any
    delta_time: float
    display_framebuffer_scale: tuple
    display_size: tuple
    font_allow_user_scaling: Any
    font_default: _ImFont
    font_global_scale: float
    fonts: _ImFontAtlas
    framerate: float
    get_clipboard_text_fn: Callable
    hover_delay_normal: float
    hover_delay_short: float
    ini_filename: str
    ini_saving_rate: float
    input_queue_characters: _ImVector_ImWchar
    input_queue_surrogate: int
    key_alt: Any
    key_ctrl: Any
    key_map: int
    key_mods: int
    key_repeat_delay: float
    key_repeat_rate: float
    key_shift: Any
    key_super: Any
    keys_data: _ImGuiKeyData
    keys_down: Any
    log_filename: str
    metrics_active_allocations: int
    metrics_active_windows: int
    metrics_render_indices: int
    metrics_render_vertices: int
    metrics_render_windows: int
    mouse_clicked: Any
    mouse_clicked_count: int
    mouse_clicked_last_count: int
    mouse_clicked_pos: tuple
    mouse_clicked_time: float
    mouse_delta: tuple
    mouse_double_click_max_dist: float
    mouse_double_click_time: float
    mouse_double_clicked: Any
    mouse_down: Any
    mouse_down_duration: float
    mouse_down_duration_prev: float
    mouse_down_owned: Any
    mouse_down_owned_unless_popup_close: Any
    mouse_drag_max_distance_abs: tuple
    mouse_drag_max_distance_sqr: float
    mouse_drag_threshold: float
    mouse_draw_cursor: Any
    mouse_hovered_viewport: int
    mouse_pos: tuple
    mouse_pos_prev: tuple
    mouse_released: Any
    mouse_wheel: float
    mouse_wheelh: float
    nav_active: Any
    nav_inputs: float
    nav_visible: Any
    pen_pressure: float
    set_clipboard_text_fn: Callable
    set_platform_ime_data_fn: Callable
    user_data: Any
    want_capture_keyboard: Any
    want_capture_mouse: Any
    want_capture_mouse_unless_popup_close: Any
    want_save_ini_settings: Any
    want_set_mouse_pos: Any
    want_text_input: Any
    def add_focus_event(self: _ImGuiIO, focused: Any) -> None: ...
    def add_input_character(self: _ImGuiIO, c: int) -> None: ...
    def add_input_character_utf16(self: _ImGuiIO, c: int) -> None: ...
    def add_input_characters_utf8(self: _ImGuiIO, str_: str) -> None: ...
    def add_key_analog_event(self: _ImGuiIO, key: Any, down: Any, value: float) -> None: ...
    def add_key_event(self: _ImGuiIO, key: Any, down: Any) -> None: ...
    def add_mouse_button_event(self: _ImGuiIO, button: int, down: Any) -> None: ...
    def add_mouse_pos_event(self: _ImGuiIO, x: float, y: float) -> None: ...
    def add_mouse_viewport_event(self: _ImGuiIO, id_: int) -> None: ...
    def add_mouse_wheel_event(self: _ImGuiIO, wheel_x: float, wheel_y: float) -> None: ...
    def clear_input_characters(self: _ImGuiIO) -> None: ...
    def clear_input_keys(self: _ImGuiIO) -> None: ...
    def destroy(self: _ImGuiIO) -> None: ...
    def gui_io() -> _ImGuiIO: ...
    def set_app_accepting_events(self: _ImGuiIO, accepting_events: Any) -> None: ...
    def set_key_event_native_data(self: _ImGuiIO, key: Any, native_keycode: int, native_scancode: int, native_legacy_index: int=-1) -> None: ...

class _ImGuiKeyData:
    analog_value: float
    down: Any
    down_duration: float
    down_duration_prev: float

class _ImGuiListClipper:
    display_end: int
    display_start: int
    items_count: int
    items_height: float
    start_posy: float
    temp_data: Any
    def begin(self: _ImGuiListClipper, items_count: int, items_height: float=-1.0) -> None: ...
    def destroy(self: _ImGuiListClipper) -> None: ...
    def end(self: _ImGuiListClipper) -> None: ...
    def force_display_range_by_indices(self: _ImGuiListClipper, item_min: int, item_max: int) -> None: ...
    def gui_list_clipper() -> _ImGuiListClipper: ...
    def step(self: _ImGuiListClipper) -> Any: ...

class _ImGuiOnceUponAFrame:
    ref_frame: int
    def destroy(self: _ImGuiOnceUponAFrame) -> None: ...
    def gui_once_upon_a_frame() -> _ImGuiOnceUponAFrame: ...

class _ImGuiPayload:
    data: Any
    data_frame_count: int
    data_size: int
    data_type: int
    delivery: Any
    preview: Any
    source_id: int
    source_parent_id: int
    def clear(self: _ImGuiPayload) -> None: ...
    def destroy(self: _ImGuiPayload) -> None: ...
    def gui_payload() -> _ImGuiPayload: ...
    def is_data_type(self: _ImGuiPayload, type_: str) -> Any: ...
    def is_delivery(self: _ImGuiPayload) -> Any: ...
    def is_preview(self: _ImGuiPayload) -> Any: ...

class _ImGuiPlatformIO:
    monitors: _ImVector_ImGuiPlatformMonitor
    platform_create_vk_surface: Callable
    platform_create_window: Callable
    platform_destroy_window: Callable
    platform_get_window_dpi_scale: Callable
    platform_get_window_focus: Callable
    platform_get_window_minimized: Callable
    platform_get_window_pos: Callable
    platform_get_window_size: Callable
    platform_on_changed_viewport: Callable
    platform_render_window: Callable
    platform_set_window_alpha: Callable
    platform_set_window_focus: Callable
    platform_set_window_pos: Callable
    platform_set_window_size: Callable
    platform_set_window_title: Callable
    platform_show_window: Callable
    platform_swap_buffers: Callable
    platform_update_window: Callable
    renderer_create_window: Callable
    renderer_destroy_window: Callable
    renderer_render_window: Callable
    renderer_set_window_size: Callable
    renderer_swap_buffers: Callable
    viewports: _ImVector_ImGuiViewportPtr
    def destroy(self: _ImGuiPlatformIO) -> None: ...
    def gui_platform_io() -> _ImGuiPlatformIO: ...

class _ImGuiPlatformImeData:
    input_line_height: float
    input_pos: tuple
    want_visible: Any
    def destroy(self: _ImGuiPlatformImeData) -> None: ...
    def gui_platform_ime_data() -> _ImGuiPlatformImeData: ...

class _ImGuiPlatformMonitor:
    dpi_scale: float
    main_pos: tuple
    main_size: tuple
    work_pos: tuple
    work_size: tuple
    def destroy(self: _ImGuiPlatformMonitor) -> None: ...
    def gui_platform_monitor() -> _ImGuiPlatformMonitor: ...

class _ImGuiStorage:
    data: _ImVector_ImGuiStoragePair
    def build_sort_by_key(self: _ImGuiStorage) -> None: ...
    def clear(self: _ImGuiStorage) -> None: ...
    def get_bool(self: _ImGuiStorage, key: int, default_val: Any=False) -> Any: ...
    def get_bool_ref(self: _ImGuiStorage, key: int, default_val: Any=False) -> Any: ...
    def get_float(self: _ImGuiStorage, key: int, default_val: float=0.0) -> float: ...
    def get_float_ref(self: _ImGuiStorage, key: int, default_val: float=0.0) -> float: ...
    def get_int(self: _ImGuiStorage, key: int, default_val: int=0) -> int: ...
    def get_int_ref(self: _ImGuiStorage, key: int, default_val: int=0) -> int: ...
    def get_void_ptr(self: _ImGuiStorage, key: int) -> Any: ...
    def get_void_ptr_ref(self: _ImGuiStorage, key: int, default_val: Any=None) -> Any: ...
    def set_all_int(self: _ImGuiStorage, val: int) -> None: ...
    def set_bool(self: _ImGuiStorage, key: int, val: Any) -> None: ...
    def set_float(self: _ImGuiStorage, key: int, val: float) -> None: ...
    def set_int(self: _ImGuiStorage, key: int, val: int) -> None: ...
    def set_void_ptr(self: _ImGuiStorage, key: int, val: Any) -> None: ...

class _ImGuiStoragePair:
    key: int
    val_f: float
    val_i: int
    val_p: Any
    def destroy(self: _ImGuiStoragePair) -> None: ...
    def float_(_key: int, _val_f: float) -> _ImGuiStoragePair: ...
    def int_(_key: int, _val_i: int) -> _ImGuiStoragePair: ...
    def ptr(_key: int, _val_p: Any) -> _ImGuiStoragePair: ...

class _ImGuiStyle:
    alpha: float
    anti_aliased_fill: Any
    anti_aliased_lines: Any
    anti_aliased_lines_use_tex: Any
    button_text_align: tuple
    cell_padding: tuple
    child_border_size: float
    child_rounding: float
    circle_tessellation_max_error: float
    color_button_position: int
    colors: tuple
    columns_min_spacing: float
    curve_tessellation_tol: float
    disabled_alpha: float
    display_safe_area_padding: tuple
    display_window_padding: tuple
    frame_border_size: float
    frame_padding: tuple
    frame_rounding: float
    grab_min_size: float
    grab_rounding: float
    indent_spacing: float
    item_inner_spacing: tuple
    item_spacing: tuple
    log_slider_deadzone: float
    mouse_cursor_scale: float
    popup_border_size: float
    popup_rounding: float
    scrollbar_rounding: float
    scrollbar_size: float
    selectable_text_align: tuple
    separator_text_align: tuple
    separator_text_border_size: float
    separator_text_padding: tuple
    tab_border_size: float
    tab_min_width_for_close_button: float
    tab_rounding: float
    touch_extra_padding: tuple
    window_border_size: float
    window_menu_button_position: int
    window_min_size: tuple
    window_padding: tuple
    window_rounding: float
    window_title_align: tuple
    def destroy(self: _ImGuiStyle) -> None: ...
    def gui_style() -> _ImGuiStyle: ...
    def scale_all_sizes(self: _ImGuiStyle, scale_factor: float) -> None: ...

class _ImGuiTableColumnSortSpecs:
    column_index: int
    column_user_id: int
    sort_direction: int
    sort_order: int
    def destroy(self: _ImGuiTableColumnSortSpecs) -> None: ...
    def gui_table_column_sort_specs() -> _ImGuiTableColumnSortSpecs: ...

class _ImGuiTableSortSpecs:
    specs: _ImGuiTableColumnSortSpecs
    specs_count: int
    specs_dirty: Any
    def destroy(self: _ImGuiTableSortSpecs) -> None: ...
    def gui_table_sort_specs() -> _ImGuiTableSortSpecs: ...

class _ImGuiTextBuffer:
    buf: _ImVector_char
    def append(self: _ImGuiTextBuffer, str_: str, str_end: str=None) -> None: ...
    def appendf(self: _ImGuiTextBuffer, fmt: str) -> None: ...
    def appendfv(self: _ImGuiTextBuffer, fmt: str, args: str) -> None: ...
    def begin(self: _ImGuiTextBuffer) -> str: ...
    def c_str(self: _ImGuiTextBuffer) -> str: ...
    def clear(self: _ImGuiTextBuffer) -> None: ...
    def destroy(self: _ImGuiTextBuffer) -> None: ...
    def empty(self: _ImGuiTextBuffer) -> Any: ...
    def end(self: _ImGuiTextBuffer) -> str: ...
    def gui_text_buffer() -> _ImGuiTextBuffer: ...
    def reserve(self: _ImGuiTextBuffer, capacity: int) -> None: ...
    def size(self: _ImGuiTextBuffer) -> int: ...

class _ImGuiTextFilter:
    count_grep: int
    filters: _ImVector_ImGuiTextRange
    input_buf: int
    def build(self: _ImGuiTextFilter) -> None: ...
    def clear(self: _ImGuiTextFilter) -> None: ...
    def destroy(self: _ImGuiTextFilter) -> None: ...
    def draw(self: _ImGuiTextFilter, label: str="Filter(inc, -exc)", width: float=0.0) -> Any: ...
    def gui_text_filter(default_filter: str="") -> _ImGuiTextFilter: ...
    def is_active(self: _ImGuiTextFilter) -> Any: ...
    def pass_filter(self: _ImGuiTextFilter, text: str, text_end: str=None) -> Any: ...

class _ImGuiTextRange:
    b: str
    e: str
    def destroy(self: _ImGuiTextRange) -> None: ...
    def empty(self: _ImGuiTextRange) -> Any: ...
    def nil() -> _ImGuiTextRange: ...
    def split(self: _ImGuiTextRange, separator: int, out: _ImVector_ImGuiTextRange) -> None: ...
    def str_(_b: str, _e: str) -> _ImGuiTextRange: ...

class _ImGuiViewport:
    dpi_scale: float
    draw_data: _ImDrawData
    flags: int
    id: int
    parent_viewport_id: int
    platform_handle: Any
    platform_handle_raw: Any
    platform_request_close: Any
    platform_request_move: Any
    platform_request_resize: Any
    platform_user_data: Any
    platform_window_created: Any
    pos: tuple
    renderer_user_data: Any
    size: tuple
    work_pos: tuple
    work_size: tuple
    def destroy(self: _ImGuiViewport) -> None: ...
    def get_center(pOut: _ImVec2, self: _ImGuiViewport) -> None: ...
    def get_work_center(pOut: _ImVec2, self: _ImGuiViewport) -> None: ...
    def gui_viewport() -> _ImGuiViewport: ...

class _ImGuiWindowClass:
    class_id: int
    dock_node_flags_override_set: int
    docking_allow_unclassed: Any
    docking_always_tab_bar: Any
    parent_viewport_id: int
    tab_item_flags_override_set: int
    viewport_flags_override_clear: int
    viewport_flags_override_set: int
    def destroy(self: _ImGuiWindowClass) -> None: ...
    def gui_window_class() -> _ImGuiWindowClass: ...

class _ImVec2:
    x: float
    y: float
    def destroy(self: _ImVec2) -> None: ...
    def float_(_x: float, _y: float) -> _ImVec2: ...
    def nil() -> _ImVec2: ...

class _ImVec4:
    w: float
    x: float
    y: float
    z: float
    def destroy(self: _ImVec4) -> None: ...
    def float_(_x: float, _y: float, _z: float, _w: float) -> _ImVec4: ...
    def nil() -> _ImVec4: ...

class _ImVector_ImDrawChannel:
    capacity: int
    data: _ImDrawChannel
    size: int

class _ImVector_ImDrawCmd:
    capacity: int
    data: _ImDrawCmd
    size: int

class _ImVector_ImDrawIdx:
    capacity: int
    data: int
    size: int

class _ImVector_ImDrawVert:
    capacity: int
    data: _ImDrawVert
    size: int

class _ImVector_ImFontAtlasCustomRect:
    capacity: int
    data: _ImFontAtlasCustomRect
    size: int

class _ImVector_ImFontConfig:
    capacity: int
    data: _ImFontConfig
    size: int

class _ImVector_ImFontGlyph:
    capacity: int
    data: _ImFontGlyph
    size: int

class _ImVector_ImFontPtr:
    capacity: int
    data: _ImFont
    size: int

class _ImVector_ImGuiPlatformMonitor:
    capacity: int
    data: _ImGuiPlatformMonitor
    size: int

class _ImVector_ImGuiStoragePair:
    capacity: int
    data: _ImGuiStoragePair
    size: int

class _ImVector_ImGuiTextRange:
    capacity: int
    data: _ImGuiTextRange
    size: int

class _ImVector_ImGuiViewportPtr:
    capacity: int
    data: _ImGuiViewport
    size: int

class _ImVector_ImTextureID:
    capacity: int
    data: Any
    size: int

class _ImVector_ImU32:
    capacity: int
    data: int
    size: int

class _ImVector_ImVec2:
    capacity: int
    data: _ImVec2
    size: int

class _ImVector_ImVec4:
    capacity: int
    data: _ImVec4
    size: int

class _ImVector_ImWchar:
    capacity: int
    data: int
    size: int

class _ImVector_char:
    capacity: int
    data: str
    size: int

class _ImVector_float:
    capacity: int
    data: float
    size: int

