from typing import Callable, Tuple, Iterable, Any, NamedTuple

class FontAtlas:
    def clear_tex_data(self): ...
    def get_tex_data_as_alpha8(self) -> Tuple[int, int, bytes]: ...
    def get_tex_data_as_rgba32(self) -> Tuple[int, int, bytes]: ...
    texture_id: Any

class ImGuiContext: ...

class ImDrawVert: ...

class ImDrawCmd:
    texture_id: Any
    clip_rect: NamedTuple[float, float, float, float]
    elem_count: int

class ImDrawIdx: ...

class ImDrawList:
    def vtx_buffer_size(self) -> int: ...
    def vtx_buffer_data(self) -> Iterable[ImDrawVert]: ...
    def idx_buffer_size(self) -> int: ...
    def idx_buffer_data(self) -> Iterable[ImDrawIdx]: ...
    def commands(self) -> Iterable[ImDrawCmd]: ...

class ImDrawData:
    def scale_clip_rects(self, width: float, height: float): ...
    def commands_lists(self) -> Iterable[ImDrawList]: ...

class ImGuiIO:
    def add_input_character(self, char: int): ...
    get_clipboard_text_fn: Callable[[str], str]
    set_clipboard_text_fn: Callable[[None, str], None]
    display_size: NamedTuple[float, float]
    display_fb_scale: NamedTuple[float, float]
    key_ctrl: bool
    key_shift: bool
    key_alt: bool
    key_super: bool
    key_map: Iterable[int]
    keys_down: Iterable[int]
    delta_time: float
    mouse_down: Iterable[int]
    mouse_pos: NamedTuple[float, float]
    mouse_wheel: float
    mouse_wheel_horizontal: float
    fonts: FontAtlas


# ---- Enums ----

KEY_TAB : int
KEY_LEFT_ARROW : int
KEY_RIGHT_ARROW : int
KEY_UP_ARROW : int
KEY_DOWN_ARROW : int
KEY_PAGE_UP : int
KEY_PAGE_DOWN : int
KEY_HOME : int
KEY_END : int
KEY_INSERT : int
KEY_DELETE : int
KEY_BACKSPACE : int
KEY_SPACE : int
KEY_ENTER : int
KEY_ESCAPE : int
KEY_A : int
KEY_C : int
KEY_V : int
KEY_X : int
KEY_Y : int
KEY_Z : int

def show_demo_window(closable=False) -> bool: ...
def get_current_context() -> ImGuiContext: ...
def create_context() -> ImGuiContext: ...
def destroy_context(ctx: ImGuiContext) -> None: ...
def new_frame() -> None: ...
def render() -> None: ...
def get_draw_data() -> ImDrawData: ...
def get_io() -> ImGuiIO: ...

def _py_vertex_buffer_vertex_pos_offset() -> Any: ...
def _py_vertex_buffer_vertex_uv_offset() -> Any: ...
def _py_vertex_buffer_vertex_col_offset() -> Any: ...
def _py_vertex_buffer_vertex_size() -> int: ...
def _py_index_buffer_index_size() -> int: ...